version: "2"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole

    env_file: .env
    volumes:
       - 'etc-pihole:/etc/pihole/'
       - './99-custom_domains.conf:/etc/dnsmasq.d/99-custom_domains.conf'
    networks:
      pihole_vlan:
        aliases:
          - pihole
        ipv4_address: 172.16.61.2
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
    
volumes:
  etc-pihole:
    
networks:
  pihole_vlan:
    driver: macvlan
    driver_opts:
      parent: enp1s0.61
    ipam:
      config:
        - subnet: 172.16.61.0/30
          gateway: 172.16.61.1
